# Supabase project configuration
project_id = "yohlethqxunrvrqkjjsh"

# Uncomment the block below only if you want to override the default
# migrations directory (which is `supabase/migrations`).
#
#[migrations]
#dir = "./migrations"