
project_id = "yohlethqxunrvrqkjjsh"

[auth.external.google]
enabled = true
client_id = "your_client_id" # This would be replaced with your actual Google client ID
secret = "your_client_secret" # This would be replaced with your actual Google client secret
redirect_uri = "https://yohlethqxunrvrqkjjsh.supabase.co/auth/v1/callback"
