
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yohlethqxunrvrqkjjsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaGxldGhxeHVucnZycWtqanNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzAwMTEsImV4cCI6MjA2MjU0NjAxMX0.krRX1jHct8wVOLm-RrKMTHI5Vt0LcY96ebUSzWKhr70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false, // Don't persist session as we're using Clerk for auth
    autoRefreshToken: false // Don't auto-refresh token as we're using Clerk for auth
  }
});

// When user is authenticated with Clerk, set their JWT as the supabase token
export const updateSupabaseAuthWithClerkSession = async (clerkToken: string | null) => {
  if (clerkToken) {
    // Set the Clerk JWT as the Supabase auth token
    supabase.auth.setSession({ access_token: clerkToken, refresh_token: '' });
    return true;
  } else {
    // Clear the session if no token is provided
    supabase.auth.setSession({ access_token: '', refresh_token: '' });
    return false;
  }
};
